name: 'Deploy React to S3'
description: 'Build and deploy React static site (built with create-react-app) to AWS S3'

inputs:
  account-number:  # id of input
    description: 'AWS account number'
    required: true
  s3-bucket:
    description: 'location of static pages'
  cloudfront-distribution:
    description: 'CloudFront Distribution ID'
    required: true
  working-directory:
    description: 'Working Directory'
    required: true
  region:
    description: 'Region'
    required: false
    default: 'eu-west-1'
  role-to-assume:
    description: 'The name of the role to role-to-assume'
    required: false
    default: 'GitHub'
  posthog-token:
    description: 'Token e.g. phc_... (optional)'
    required: false
  sentry-environment:
    description: 'Environment for Sentry error monitoring'
    required: false
  githash:
    description: 'Commit ID being deployed'
    required: false

runs:
  using: "composite"
  steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Install third party dependencies
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: npm install
        
      - name: Build docs
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: npm run build
        env:
          REACT_APP_POSTHOG_TOKEN: '${{ inputs.posthog-token }}'
          REACT_APP_SENTRY_ENVIRONMENT: '${{ inputs.sentry-environment }}'
          REACT_APP_GITHASH: '${{ inputs.githash }}'
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account-number }}:role/${{ inputs.role-to-assume }}
          role-session-name: rolesession
          aws-region: ${{ inputs.region }}
        
      - name: Upload to S3
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: |
          aws s3 sync --delete build s3://${{ inputs.s3-bucket }}
          
      - name: Invalidate Cache
        shell: bash
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution }} --paths /index.html
