name: 'Archive Repository'
description: 'Archive this repository and set version'
inputs:
  project-name:  # id of input
    description: 'Name of this project'
    required: true
  package-version:  # id of input
    description: 'Version this package'
    required: true
runs:
  using: "composite"
  steps:
    # Archive this repository
    - name: Create a tar file of this repository
      shell: bash
      run: |
        git archive --format tar --output ${{ inputs.project-name }}-${{ inputs.package-version }}.tar HEAD

    # Upload to GitHub
    - name: upload to GitHub workflow
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ inputs.project-name }}-${{ inputs.package-version }}.tar
        retention-days: 1
