name: 'Distribute repo behind VPN'
description: 'Take this .git file and copy to location behind VPN'
inputs:
  project-name:  # id of input
    description: 'Name of project to upload'
    required: true
  package-version:  # id of input
    description: 'Version number of this project'
    required: true
runs:
  using: "composite"
  steps:
    # Move to a location that can be accessed at packages.arup.com
    - name: Move package to download location
      shell: bash
      run: |
        mv package/.git ~/git/repos/${{ inputs.project-name }}-${{ inputs.package-version }}.git
        cp -f ~/git/repos/${{ inputs.project-name }}-${{ inputs.package-version }}.tar ~/git/repos/${{ inputs.project-name }}.tar
        rm -rf package
